"""Build the EotG observer sub-mod's overlay files (balance spec §9.2).

The observer needs hooks inside the main mod's scripted effects, on_actions,
decisions, story cycles, character interactions, tamper events and patron
events. CK3 replaces a file when a later-loaded mod ships the same relative
path, so this script copies those seven main-mod files into
the sub-mod and inserts one-line hooks, each tagged `# eotg_obs`. It then
checks that removing every tagged line gives back the main-mod file byte for
byte: the overlay changes nothing but logging.

The sources live in the repo at docs/tools/observer/ and are never loaded by
the main mod. The build writes a complete, installable sub-mod to --out, which
is normally the CK3 mod folder, so the generated overlays never enter the repo.

RE-RUN THIS AFTER EVERY CHANGE TO THE MAIN MOD'S SEVEN FILES. A stale overlay
would run old gameplay code. The header of each overlay records the source
file's SHA-1; `--check` reports a mismatch.

Usage:
  python tools/build_observer.py --out "<CK3 mod folder>/eotg_observer_submod" [--mod <main mod root>]
  python tools/build_observer.py --out "<same folder>" --check
"""

import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))   # docs/tools
import textio  # noqa: E402  (one BOM at most: docs/pitfalls.md §14)

HERE = Path(__file__).resolve().parents[1]          # the sub-mod sources (docs/tools/observer)
MOD = HERE.parents[2]                                # the main mod: repo root, three levels up
OUT = None                                           # build output, set by --out
TAG = "  # eotg_obs"

FILES = {
    "effects": "common/scripted_effects/eotg_augmentation_effects.txt",
    "on_actions": "common/on_action/eotg_augmentation_on_actions.txt",
    "decisions": "common/decisions/eotg_augmentation_decisions.txt",
    "stories": "common/story_cycles/eotg_augmentation_stories.txt",
    # Interactions spec §9 item 10 (the five interaction counters)
    "interactions": "common/character_interactions/eotg_augmentation_interactions.txt",
    "tamper": "events/eotg_augmentation_tamper.txt",
    # Reprisal spec §9 item 7 (the three reprisal counters)
    "patron": "events/eotg_augmentation_patron.txt",
}
YEARLY_LISTS = (
    "eotg_on_yearly_aug_initiation_check",
    "eotg_on_yearly_aug_tier1_check",
    "eotg_on_yearly_aug_tier2_check",
    "eotg_on_yearly_aug_overclocked_check",
    "eotg_on_yearly_aug_neurofractured_check",
)


def read(p):
    return textio.read_text(p)[0]


def sha(text):
    return hashlib.sha1(text.encode("utf-8")).hexdigest()


def top_blocks(lines):
    """(name, first_line, last_line) of every top-level `name = {` block."""
    out, name, start, depth = [], None, 0, 0
    for i, line in enumerate(lines):
        code = line.split("#", 1)[0]
        if depth == 0:
            m = re.match(r"^([A-Za-z_][\w.]*)\s*=\s*\{", code)
            if m:
                name, start = m.group(1), i
        depth += code.count("{") - code.count("}")
        if depth == 0 and name is not None and ("{" in code or "}" in code):
            out.append((name, start, i))
            name = None
    return out


def indent_of(line):
    return line[: len(line) - len(line.lstrip())]


class Overlay:
    def __init__(self, rel):
        self.rel = rel
        self.src = read(MOD / rel)
        self.lines = self.src.split("\n")
        self.inserts = {}          # line index -> [lines to insert BEFORE it]
        self.after = {}            # line index -> [lines to insert AFTER it]
        self.count = 0

    def before(self, i, text, ind=None):
        ind = indent_of(self.lines[i]) if ind is None else ind
        self.inserts.setdefault(i, []).append(ind + text + TAG)
        self.count += 1

    def after_line(self, i, text, extra="    "):
        self.after.setdefault(i, []).append(indent_of(self.lines[i]) + extra + text + TAG)
        self.count += 1

    def find(self, pattern, lo=0, hi=None, n=1):
        hi = len(self.lines) if hi is None else hi
        hits = [i for i in range(lo, hi) if re.search(pattern, self.lines[i])]
        if len(hits) != n:
            sys.exit(f"anchor {pattern!r} in {self.rel}: {len(hits)} hits, expected {n}")
        return hits

    def block(self, name):
        for b, s, e in top_blocks(self.lines):
            if b == name:
                return s, e
        sys.exit(f"block {name} not found in {self.rel}")

    def render(self):
        out = []
        for i, line in enumerate(self.lines):
            out += self.inserts.get(i, [])
            out.append(line)
            out += self.after.get(i, [])
        header = (f"# eotg_obs OVERLAY of the main mod's {self.rel}\n"
                  f"# eotg_obs source sha1 {sha(self.src)}; {self.count} hook lines tagged '# eotg_obs'.\n"
                  f"# eotg_obs Generated by tools/build_observer.py. Do not edit; rebuild instead.\n")
        text = header + "\n".join(out)
        # Proof: dropping the tagged lines restores the source exactly.
        restored = "\n".join(l for l in text.split("\n") if not l.endswith(TAG) and not l.startswith("# eotg_obs "))
        assert restored == self.src, f"{self.rel}: overlay differs from source beyond hook lines"
        return text


def build_effects():
    o = Overlay(FILES["effects"])
    s, e = o.block("eotg_aug_initiate_effect")
    i = o.find(r"limit = \{ eotg_is_augmented_any = no \}", s, e)[0]
    o.after_line(i, "eotg_obs_log_init_effect = yes", extra="")
    s, e = o.block("eotg_aug_set_integration_effect")
    i = o.find(r"add_trait_xp = \{", s, e)[0]
    o.before(i, "eotg_obs_log_integration_effect = { XP = $XP$ }")
    for name, line in (
        ("eotg_trigger_neurofracture", "eotg_obs_log_effect = { KEY = cascade_ruler }"),
        # Realm spec §4.9 counter 4: cascades of rulers with a technician
        ("eotg_trigger_neurofracture", "if = { limit = { eotg_aug_own_technician_valid = yes } eotg_obs_log_effect = { KEY = cascade_tech } }"),
        # Self-repair spec §4.3 counters 2 and 3: cascades of fitted rulers,
        # and of those with the full stack (before the cascade removes the trait)
        ("eotg_trigger_neurofracture", "eotg_obs_log_self_repair_effect = { PREFIX = cascade }"),
        # Self-repair spec §4.3 counter 1: refits
        ("eotg_aug_self_repair_fit_effect", "eotg_obs_log_effect = { KEY = refit }"),
        ("eotg_aug_nr_cascade_effect", "eotg_obs_log_effect = { KEY = cascade_nonruler }"),
        ("eotg_aug_cascade_death_effect", "eotg_obs_log_term_effect = { KIND = death }"),
        ("eotg_aug_total_integration_effect", "eotg_obs_log_term_effect = { KIND = seamless }"),
        ("eotg_aug_excision_effect", "eotg_obs_log_term_effect = { KIND = excision }"),
        ("eotg_aug_abdicate_effect", "eotg_obs_log_term_effect = { KIND = abdication }"),
    ):
        s, e = o.block(name)
        o.after_line(s, line, extra="    ")
    s, e = o.block("eotg_aug_excision_surgery_effect")
    i = o.find(r"death = \{ death_reason = death_treatment \}", s, e)[0]
    o.before(i, "eotg_obs_log_term_effect = { KIND = excision_death }")
    # Interactions spec §9 item 10: Offer (landed / unlanded), Demand,
    # Salvage and deaths on the table
    s, e = o.block("eotg_aug_offer_install_effect")
    o.after_line(s, "scope:recipient = { eotg_obs_log_offer_effect = yes }", extra="    ")
    s, e = o.block("eotg_aug_demand_removal_effect")
    o.after_line(s, "scope:recipient = { eotg_obs_log_effect = { KEY = int_demand } }", extra="    ")
    s, e = o.block("eotg_aug_salvage_effect")
    o.after_line(s, "scope:recipient = { eotg_obs_log_effect = { KEY = int_salvage } }", extra="    ")
    i = o.find(r"add_kinslayer_trait_or_nothing_effect = \{ VICTIM = scope:recipient \}", s, e)[0]
    o.before(i, "eotg_obs_log_effect = { KEY = int_salvage_death }")
    # Reprisal spec §9 item 7: collector schemes started (the collector's id,
    # flagged for the observer's on_death), and the fallback
    s, e = o.block("eotg_aug_patron_collect_effect")
    i = o.find(r"^\s*start_scheme = \{", s, e)[0]
    o.before(i, "add_character_flag = eotg_obs_collector")
    o.before(i, "eotg_obs_log_effect = { KEY = collector_scheme }")
    i = o.find(r"remove_short_term_gold = medium_gold_value", s, e)[0]
    o.before(i, "eotg_obs_log_effect = { KEY = collector_fallback }")
    # Realm spec §4.9 counter 3: contraband crimes (the subject's id)
    s, e = o.block("eotg_aug_contraband_effect")
    i = o.find(r"save_scope_as = eotg_contraband_subject", s, e)[0]
    o.before(i, "eotg_obs_log_effect = { KEY = crime_contraband }")
    for name, story, key in (
        ("eotg_aug_try_start_countdown_effect", "eotg_story_aug_countdown", "cd_start"),
        ("eotg_aug_patron_accept_effect", "eotg_story_aug_patron", "arc_patron_start"),
        ("eotg_aug_start_retinue_effect", "eotg_story_aug_retinue", "arc_retinue_start"),
    ):
        s, e = o.block(name)
        i = o.find(r"create_story = " + story, s, e)[0]
        o.before(i, f"eotg_obs_log_effect = {{ KEY = {key} }}")
    return o


def build_on_actions():
    o = Overlay(FILES["on_actions"])
    for name in YEARLY_LISTS:
        s, e = o.block(name)
        hits = [i for i in range(s, e) if re.search(r"^\s*trigger_event = \{ id = ", o.lines[i])]
        if not hits:
            sys.exit(f"no trigger_event in {name}")
        for i in hits:
            o.before(i, "eotg_obs_log_event_effect = yes")
    for name, key in (("eotg_on_yearly_aug_overclocked_check", "arc_heir_start_oc"),
                      ("eotg_on_yearly_aug_neurofractured_check", "arc_heir_start_nf")):
        s, e = o.block(name)
        i = o.find(r"create_story = eotg_story_aug_heir_arc", s, e)[0]
        o.before(i, f"eotg_obs_log_effect = {{ KEY = {key} }}")
    return o


def build_decisions():
    o = Overlay(FILES["decisions"])
    keys = []
    for name, s, e in top_blocks(o.lines):
        if not name.startswith("eotg_decision_"):
            continue
        i = o.find(r"^    effect = \{\s*$", s, e)[0]
        short = name[len("eotg_decision_"):]
        keys.append("dec_" + short)
        o.after_line(i, f"eotg_obs_log_effect = {{ KEY = dec_{short} }}")
        if name == "eotg_decision_seek_augmentation":
            o.after_line(i, "hidden_effect = { add_character_flag = { flag = eotg_obs_sought  years = 1 } }")
        if name == "eotg_decision_aug_pursue_next_stage":
            o.after_line(i, "hidden_effect = { add_character_flag = { flag = eotg_obs_pursued  years = 1 } }")
    return o, keys


def build_stories():
    o = Overlay(FILES["stories"])
    s, e = o.block("eotg_story_aug_countdown")
    for i in range(s, e):
        m = re.search(r"trigger_event = \{ id = (eotg_aug_countdown\.00(\d)|eotg_aug_tier3\.020)", o.lines[i])
        if m:
            key = f"cd_{m.group(2)}" if m.group(2) else "cd_t3020"
            o.before(i, f"debug_log = eotg_obs_{key}")
    for name, arc in (("eotg_story_aug_heir_arc", "heir"), ("eotg_story_aug_countdown", "cd"),
                      ("eotg_story_aug_patron", "patron"), ("eotg_story_aug_retinue", "retinue")):
        s, e = o.block(name)
        i = o.find(r"^    on_end = \{", s, e)[0]
        o.after_line(i, f"story_owner ?= {{ eotg_obs_log_arc_end_effect = {{ ARC = {arc} }} }}")
    return o


def build_interactions():
    """Examine and Tamper start: logged on the click (on_accept), actor's id."""
    o = Overlay(FILES["interactions"])
    for name, key in (("eotg_aug_examine_interaction", "int_examine"),
                      ("eotg_aug_start_tamper_interaction", "tamper_start")):
        s, e = o.block(name)
        i = o.find(r"^    on_accept = \{\s*$", s, e)[0]
        o.after_line(i, f"scope:actor = {{ eotg_obs_log_effect = {{ KEY = {key} }} }}")
    # Realm spec §4.9 counter 3: a refused Demand that was a crime (the
    # refuser's id)
    s, e = o.block("eotg_aug_demand_removal_interaction")
    i = o.find(r"^\s*reverse_add_opinion = \{", s, e)[0]
    o.before(i, "eotg_obs_log_effect = { KEY = crime_defied }")
    return o


def build_tamper():
    """tamper.001's result roll: success / failure, and the execution-roll
    discovery (owner's id). Mid-scheme breaches are vanilla's and not counted."""
    o = Overlay(FILES["tamper"])
    s, e = o.block("eotg_aug_tamper.001")
    for event, key in (("eotg_aug_tamper.002", "tamper_success"), ("eotg_aug_tamper.003", "tamper_failure")):
        i = o.find(r"trigger_event = \{ id = " + re.escape(event), s, e)[0]
        o.before(i, f"eotg_obs_log_effect = {{ KEY = {key} }}")
        o.before(i, "if = { limit = { exists = scope:scheme_discovered } eotg_obs_log_effect = { KEY = tamper_discovered } }")
    return o


def build_patron():
    """Reprisal spec §9 item 7: .006 f by owner state; .009 fired and the
    option taken (owner's id)."""
    o = Overlay(FILES["patron"])
    s, e = o.block("eotg_aug_patron.006")
    i = o.find(r"name = eotg_aug_patron" + re.escape(".006.f") + r"$", s, e)[0]
    o.after_line(i, "if = { limit = { eotg_is_augmented_any = yes } eotg_obs_log_effect = { KEY = patron_f_aug } } "
                    "else = { eotg_obs_log_effect = { KEY = patron_f_none } }", extra="")
    s, e = o.block("eotg_aug_patron.009")
    i = o.find(r"^    immediate = \{\s*$", s, e)[0]
    o.after_line(i, "eotg_obs_log_effect = { KEY = patron_009 }")
    for x in "abcde":
        i = o.find(r"name = eotg_aug_patron" + re.escape(".009." + x) + r"$", s, e)[0]
        o.after_line(i, f"eotg_obs_log_effect = {{ KEY = patron_009_{x} }}", extra="")
    return o


STATES = ("none", "t1", "t2", "t3", "nf", "ti")
TTS = ("county", "duchy", "kingdom")


def loc_keys(dec_keys):
    glob = ["start", "year", "census_begin", "census_end", "census_innovation"]
    char = []
    for p in ("census", "ev"):
        char += [f"{p}_{s}_{t}" for s in STATES for t in TTS]
    char += [f"knight_{s}_all" for s in STATES]
    char += ["dev_lt10", "dev_10_14", "dev_15_19", "dev_20_34", "dev_35p", "nf_sedated",
             "gold_t1_ok", "gold_t1_fail", "gold_t2_ok", "gold_t2_fail",
             "death_nf", "death_ti", "init_seek", "init_random", "init_nonruler",
             "prog_12_pursue", "prog_12_offer", "prog_12_nonruler",
             "prog_23_pursue", "prog_23_offer", "prog_23_nonruler",
             "regress_32", "regress_21", "cascade_ruler", "cascade_nonruler",
             "courses_0", "courses_1", "courses_2", "courses_3p",
             "cd_start", "cd_1", "cd_2", "cd_3", "cd_4", "cd_5", "cd_6", "cd_t3020",
             "arc_heir_start_oc", "arc_heir_start_nf", "arc_patron_start", "arc_retinue_start"]
    char += [f"term_{k}" for k in ("death", "seamless", "excision", "abdication", "excision_death")]
    char += [f"arc_{a}_{x}" for a in ("heir", "cd", "patron", "retinue") for x in ("end", "end_death")]
    char += ["int_offer_landed", "int_offer_unlanded", "int_demand", "int_examine",
             "tamper_start", "tamper_success", "tamper_failure", "tamper_discovered",
             "int_salvage", "int_salvage_death"]
    # Realm spec §4.9
    char += [f"{p}_{law}" for p in ("census_law", "init_law") for law in ("ban", "license", "favor", "none")]
    char += ["census_technician", "crime_contraband", "crime_defied", "cascade_tech"]
    # Reprisal spec §9 item 7
    char += ["patron_f_aug", "patron_f_none", "patron_009"] + [f"patron_009_{x}" for x in "abcde"]
    char += ["collector_scheme", "collector_fallback", "collector_kill"]
    # Self-repair spec §4.3
    char += ["census_self_repair", "census_full_stack", "cascade_self_repair", "cascade_full_stack", "refit"]
    char += dec_keys
    lines = ["l_english:"]          # write() adds the BOM
    for k in glob:
        lines.append(f' eotg_obs_{k}:0 "EOTG_OBS {k} y=[GetCurrentDate.GetYear]"')
    for k in char:
        lines.append(f' eotg_obs_{k}:0 "EOTG_OBS {k} y=[GetCurrentDate.GetYear] id=[THIS.GetCharacter.GetID]"')
    return "\n".join(lines) + "\n"


def write(rel, text):
    """Every sub-mod script and loc file: exactly one BOM, however many the source had."""
    textio.write_text(str(OUT / rel), text, bom=True, makedirs=True)


def main(argv):
    global MOD, OUT
    if "--mod" in argv:
        MOD = Path(argv[argv.index("--mod") + 1])
    if "--out" not in argv:
        sys.exit("--out <folder> is required, normally <CK3 mod folder>/eotg_observer_submod (see README)")
    OUT = Path(argv[argv.index("--out") + 1]).resolve()
    if MOD.resolve() in OUT.parents or OUT == MOD.resolve():
        sys.exit("--out must be outside the main mod: the overlays would shadow its files")
    if "--check" in argv:
        bad = 0
        for rel in FILES.values():
            ov = OUT / rel
            if not ov.exists():
                print("missing overlay", rel); bad += 1; continue
            m = re.search(r"source sha1 ([0-9a-f]+)", read(ov))
            if not m or m.group(1) != sha(read(MOD / rel)):
                print("STALE overlay (main mod changed):", rel); bad += 1
        print("overlays up to date" if not bad else "rebuild with: python tools/build_observer.py --out <same folder>")
        return 1 if bad else 0
    eff = build_effects()
    oa = build_on_actions()
    dec, dec_keys = build_decisions()
    st = build_stories()
    ia = build_interactions()
    tp = build_tamper()
    pt = build_patron()
    for o in (eff, oa, dec, st, ia, tp, pt):
        write(o.rel, o.render())
        print(f"{o.rel}: {o.count} hook lines")
    write("localization/english/eotg_observer_l_english.yml", loc_keys(dec_keys))
    # The sub-mod's own script files carry a BOM like the main mod's.
    for rel in ("common/on_action/eotg_observer_on_actions.txt",
                "common/scripted_effects/eotg_observer_effects.txt"):
        write(rel, read(HERE / rel))
    # The descriptor goes inside the sub-mod; the launcher .mod goes beside it,
    # which is where CK3 looks when OUT is <CK3 mod folder>/eotg_observer_submod.
    textio.write_text(str(OUT / "descriptor.mod"), read(HERE / "descriptor.mod"), bom=False)
    textio.write_text(str(OUT.parent / "eotg_observer_submod.mod"),
                      read(HERE / "eotg_observer_submod.mod"), bom=False)
    print("decisions hooked:", len(dec_keys))
    print("built:", OUT)
    print("launcher:", OUT.parent / "eotg_observer_submod.mod")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
