"""Generate the projector beam as an .obj frustum - the cone of light the emblem floats in.

The marker is meant to read as a hologram standing on a plinth, so the plinth has to be seen
projecting it. That is this: an open, untapered-at-neither-end cone rising from the pedestal's top
face and widening to swallow the emblem.

WHY GEOMETRY AND NOT A SHADER TRICK. There is no volumetric anything available here. A beam has to
be a surface, and a surface that is meant to look like light has to blend. That rules out the
effect the other two slots use - `snap_to_terrain` is opaque - and it is why the beam gets its own
material slot running `snap_to_terrain_alpha_to_coverage`: a *vanilla* effect name (new ones do not
register) that both snaps to terrain, as every slot must, and carries BlendEnable with
SRC_ALPHA/INV_SRC_ALPHA, so it blends whether or not the player has MSAA on.

SHAPE NOTES, all of which are load-bearing:
  * Open tube, no caps. A cap at the base draws a bright disc sitting on the plinth, which reads as
    a coin rather than as the mouth of a projector.
  * Single layer by way of backface culling. A translucent closed volume has to sort its own front
    and back faces against each other and cannot, so it shimmers as the camera turns. Drawing only
    front faces gives exactly one layer of blend per pixel and is stable from every angle.
  * v runs 0 at the base to 1 at the top, so the diffuse's alpha gradient runs ALONG the beam and
    the fade is authored in the texture rather than in the shader.
  * Normals are the true outward radial of the slope, tilted by (r0 - r1) / h and NOT simply
    horizontal. The shader fades alpha on dot(N, view) to fake thickness - brightest through the
    middle where you look down the length of the cone, falling off at the silhouette - and that
    only lands if the normals actually follow the surface.

Winding is emitted outward-facing and is checked, not trusted: obj_to_pdxmesh.check_winding
compares every face's cross product against its authored normal and refuses to write a mesh that
is inside out. An inverted beam is invisible, which looks identical to a missing file.

Usage:  python docs/tools/make_beam_obj.py <out.obj> [--segments 48] [--r0 0.5] [--r1 1.2]
                                           [--y0 0.0] [--height 2.0]
"""
from __future__ import annotations

import argparse
import math


def beam_obj(path: str, segments: int, r0: float, r1: float, y0: float, height: float) -> None:
    """Write an open frustum: radius r0 at y0, radius r1 at y0 + height."""
    # Slope of the wall, used for the normal's vertical component. A straight cylinder (r0 == r1)
    # gives s = 0 and purely horizontal normals, which is correct for that case.
    s = (r0 - r1) / height if height else 0.0
    inv = 1.0 / math.sqrt(1.0 + s * s)

    P, N, T, F = [], [], [], []
    # The seam is duplicated (<= segments, not < segments) so u can reach 1.0. Sharing the seam
    # vertex would wrap u from 1 back to 0 across one quad and mirror the whole texture into it.
    for i in range(segments + 1):
        u = i / segments
        th = u * 2.0 * math.pi
        c, sn = math.cos(th), math.sin(th)
        P.append((r0 * c, y0, r0 * sn))
        P.append((r1 * c, y0 + height, r1 * sn))
        N.append((c * inv, s * inv, sn * inv))
        N.append((c * inv, s * inv, sn * inv))
        T.append((u, 0.0))
        T.append((u, 1.0))

    # Outward-facing winding. Derived, not guessed: for the quad at theta = 0, where outward is +X,
    # (b_i, t_i, b_i+1) has cross product (B-A)x(C-A) pointing along +X, and the naive
    # (b_i, b_i+1, t_i) points along -X - i.e. straight into the cone.
    for i in range(segments):
        b0, t0 = 2 * i + 1, 2 * i + 2                 # .obj indices are 1-based
        b1, t1 = 2 * (i + 1) + 1, 2 * (i + 1) + 2
        F.append((b0, t0, b1))
        F.append((b1, t0, t1))

    L = ["# MOD(eotg) GENERATED by docs/tools/make_beam_obj.py - do not hand-edit.",
         "# Open frustum, %d segments, r %.3f -> %.3f over height %.3f." % (segments, r0, r1, height)]
    L += ["v %.6f %.6f %.6f" % p for p in P]
    L += ["vt %.6f %.6f" % t for t in T]
    L += ["vn %.6f %.6f %.6f" % n for n in N]
    L += ["f %d/%d/%d %d/%d/%d %d/%d/%d" % (a, a, a, b, b, b, c, c, c) for a, b, c in F]
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--segments", type=int, default=48)
    ap.add_argument("--r0", type=float, default=0.5)
    ap.add_argument("--r1", type=float, default=1.2)
    ap.add_argument("--y0", type=float, default=0.0)
    ap.add_argument("--height", type=float, default=2.0)
    a = ap.parse_args()
    beam_obj(a.out, a.segments, a.r0, a.r1, a.y0, a.height)
    print("wrote %s  (%d segments, r %.2f -> %.2f, y %.2f..%.2f)"
          % (a.out, a.segments, a.r0, a.r1, a.y0, a.y0 + a.height))


if __name__ == "__main__":
    main()
