"""Generate a lathed province-marker solid as a .obj, ready for obj_to_pdxmesh.py.

Why generate rather than model: a lathe is fully described by a profile, so the shape is a table
of numbers that can be tuned in one line and rebuilt, and the result is watertight by
construction - which the asteroid attempt proved is the hard part. Every vanilla map mesh but two
is an open shell, and an open shell renders with holes.

The profile is a list of (radius, height) in model units, bottom to top. The surface is revolved
around Y; caps close the bottom and top. Vertices are duplicated per band, so horizontal edges
stay crisp while the curvature around the axis shades smoothly - the correct convention for a
turned object, and what stops a stepped podium from looking like a melted cone.

Profiles:
  podium  - a stepped dais with a flat top. Reads as a plinth that something stands on.
  chess   - a pawn/rook base: plinth, collar, tapered neck, flared cap.
  disc    - a plain two-step puck, for when the marker should not compete with anything.

Usage:  python docs/tools/make_marker_obj.py podium out.obj [--segments 48]
"""
from __future__ import annotations

import argparse
import math
import sys

import numpy as np

# (radius, y). Normalised so the widest radius is 1.0 and the top is the overall height; the
# caller scales the whole thing at conversion time.
PROFILES = {
    # Wide, low, unmistakably a platform. The 0.02 lip at the very bottom keeps the base edge
    # from z-fighting the terrain it is snapped to.
    "podium": [
        (0.00, 0.00),
        (1.00, 0.00),
        (1.00, 0.16),
        (0.88, 0.24),
        (0.88, 0.40),
        (0.74, 0.48),
        (0.74, 0.62),
        (0.60, 0.68),
        (0.00, 0.68),
    ],
    # Taller, with the waist and flare that make a chess piece read as one at a glance.
    "chess": [
        (0.00, 0.00),
        (1.00, 0.00),
        (1.00, 0.14),
        (0.92, 0.22),
        (0.70, 0.34),
        (0.52, 0.46),
        (0.44, 0.68),
        (0.42, 0.92),
        (0.56, 1.02),
        (0.62, 1.12),
        (0.50, 1.20),
        (0.00, 1.22),
    ],
    "disc": [
        (0.00, 0.00),
        (1.00, 0.00),
        (1.00, 0.18),
        (0.78, 0.26),
        (0.78, 0.40),
        (0.00, 0.40),
    ],
}


def lathe(profile, segments):
    """Revolve `profile` around Y. Returns (positions, normals, uvs, faces) as .obj index lists.

    A segment of the profile with zero radius change is a cylinder wall; one with zero height
    change is a flat annulus. Both fall out of the same code - the normal is just perpendicular
    to the profile segment, rotated into place.
    """
    P, N, T, F = [], [], [], []

    # arc length along the profile, for a V coordinate that does not stretch
    lengths = [0.0]
    for a, b in zip(profile, profile[1:]):
        lengths.append(lengths[-1] + math.hypot(b[0] - a[0], b[1] - a[1]))
    total = lengths[-1]

    for k, ((r0, y0), (r1, y1)) in enumerate(zip(profile, profile[1:])):
        if abs(r1 - r0) < 1e-9 and abs(y1 - y0) < 1e-9:
            continue
        # profile tangent -> outward normal in the (radial, Y) plane
        dr, dy = r1 - r0, y1 - y0
        ln = math.hypot(dr, dy)
        nr, ny = dy / ln, -dr / ln
        v0, v1 = lengths[k] / total, lengths[k + 1] / total

        base = len(P)
        for s in range(segments + 1):          # +1 so the UV seam does not wrap
            ang = 2.0 * math.pi * s / segments
            ca, sa = math.cos(ang), math.sin(ang)
            u = s / segments
            for (r, y, v) in ((r0, y0, v0), (r1, y1, v1)):
                P.append((r * ca, y, r * sa))
                N.append((nr * ca, ny, nr * sa))
                T.append((u, v))
        for s in range(segments):
            a = base + s * 2
            b, c, d = a + 1, a + 2, a + 3      # a,b = this ring lo/hi; c,d = next ring
            # Winding must agree with the outward normal above or every face is backface-culled
            # and the whole model renders as nothing. Do not reason about it - check_winding()
            # measures it, and the first version of this loop had all 960 triangles inverted.
            if r0 > 1e-9:
                F.append((a, b, c))
            if r1 > 1e-9:
                F.append((b, d, c))
    return P, N, T, F


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("profile", choices=sorted(PROFILES))
    ap.add_argument("out")
    ap.add_argument("--segments", type=int, default=48)
    a = ap.parse_args()

    P, N, T, F = lathe(PROFILES[a.profile], a.segments)
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("# generated by docs/tools/make_marker_obj.py %s\n" % a.profile)
        f.write("o eotg_marker_%s\n" % a.profile)
        for p in P:
            f.write("v %.6f %.6f %.6f\n" % p)
        for t in T:
            f.write("vt %.6f %.6f\n" % t)
        for n in N:
            f.write("vn %.6f %.6f %.6f\n" % n)
        for tri in F:
            f.write("f %s\n" % " ".join("%d/%d/%d" % (i + 1, i + 1, i + 1) for i in tri))

    v = np.array(P, np.float64)
    lo, hi = v.min(0), v.max(0)
    print("wrote %s" % a.out)
    print("  verts %d  tris %d" % (len(P), len(F)))
    print("  size %.3f x %.3f x %.3f   minY %.3f" % (hi[0]-lo[0], hi[1]-lo[1], hi[2]-lo[2], lo[1]))


if __name__ == "__main__":
    main()
