"""Switch off the vanilla 3D map objects that do not belong on a galaxy map.

Trees, reeds, deer, medieval stone bridges, coastal cliffs, the Great Wall and the map-table
props are all placed as map objects. None of them belong here, and several are the loudest
remaining medieval tells once the terrain stops looking like earth.

HOW, and why this way. Each file in gfx/map/map_object_data declares objects as

    object={ name="..." ... count=N transform="<packed instance data>" }

where `count` is how many instances are placed and `transform` carries their positions. Setting
count=0 with an empty transform is a supported state, not a hack: vanilla ships coast_foam.txt
exactly like that. The alternative - disabling whole layers in layers.txt - was rejected because
several of these share a layer with things that must stay. `animals` sits on `unit_layer`
alongside actual armies, and `audio_emitters` sits on `building_layer` alongside our holding
markers, so a layer-level switch would take those with it.

KEPT deliberately:
  lakes            232 water surfaces. Removing them leaves holes where lakes should be.
  audio_emitters   1372, and no geometry at all - ambience only.
  coast_foam       already count=0 in vanilla.
  *_locators       anchor points, not models.

Usage:  python docs/tools/strip_map_objects.py <mod root>
"""
from __future__ import annotations

import os
import re
import sys

GAME = r"D:\SteamLibrary\steamapps\common\Crusader Kings III\game"
REL = os.path.join("gfx", "map", "map_object_data")

# Everything here is emptied. The generated/ folder is added at runtime - it is all foliage.
STRIP = [
    "animals.txt",                 # deer, birds and the like
    "bridges.txt",                 # stone bridges
    "cliffs_coastline.txt",        # coastal rock
    "env_effects.txt",             # coastal mist and spray
    "great_wall_china.txt",
    "great_wall_china_gate.txt",
    "changan_building.txt",
    "special.txt",                 # special-building models
    "map_table_ce1.txt",           # the map-table props
    "map_table_ep3.txt",
    "map_table_tgp.txt",
    "map_table_western.txt",
]

HEADER = ("\ufeff# MOD(eotg) GENERATED by docs/tools/strip_map_objects.py - do not hand-edit.\n"
          "# Every object is declared exactly as vanilla declares it, with count=0 and an empty\n"
          "# transform, which is how vanilla itself ships coast_foam.txt. The objects still exist\n"
          "# so nothing that references them breaks; there are simply no instances placed.\n\n")


def strip_file(src: str, dst: str) -> tuple[int, int]:
    """Rewrite one map-object file with every instance count set to zero."""
    txt = open(src, encoding="utf-8-sig").read()
    before = sum(int(n) for n in re.findall(r"count=(\d+)", txt))

    out, n_obj = [], 0
    for block in re.finditer(r"object=\{(.*?)\}", txt, re.S):
        body = block.group(1)
        name = re.search(r'name="([^"]*)"', body)
        layer = re.search(r'layer="([^"]*)"', body)
        rp = re.search(r"render_pass=(\w+)", body)
        lines = ["object={"]
        if name:
            lines.append('\tname="%s"' % name.group(1))
        if rp:
            lines.append("\trender_pass=%s" % rp.group(1))
        if layer:
            lines.append('\tlayer="%s"' % layer.group(1))
        lines += ["\tcount=0", '\ttransform=""}']
        out.append("\n".join(lines))
        n_obj += 1

    open(dst, "w", encoding="utf-8", newline="\n").write(HEADER + "\n".join(out) + "\n")
    return n_obj, before


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    outdir = os.path.join(sys.argv[1], REL)
    os.makedirs(os.path.join(outdir, "generated"), exist_ok=True)

    targets = [(f, f) for f in STRIP]
    gen = os.path.join(GAME, REL, "generated")
    if os.path.isdir(gen):
        targets += [(os.path.join("generated", f), os.path.join("generated", f))
                    for f in sorted(os.listdir(gen)) if f.endswith(".txt")]

    total_objs = total_inst = 0
    for rel_src, rel_dst in targets:
        src = os.path.join(GAME, REL, rel_src)
        if not os.path.exists(src):
            print("  skipped, not in this install: %s" % rel_src)
            continue
        n, inst = strip_file(src, os.path.join(outdir, rel_dst))
        total_objs += n
        total_inst += inst
        print("  %-42s %3d objects, %6d instances removed" % (rel_dst, n, inst))
    print("\n%d objects across %d files; %d placed instances removed"
          % (total_objs, len(targets), total_inst))


if __name__ == "__main__":
    main()
